// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }







import type { Metadata } from "next";
import Navbar from '@/components/Navbar';
import { Yatra_One, Mukta } from "next/font/google";
import "./globals.css";
import Loader from "@/components/Loader";

const yatraOne = Yatra_One({
  weight: "400",
  subsets: ["devanagari"],
  variable: "--font-yatra",
  display: "swap",
});

const mukta = Mukta({
  weight: ["300", "400", "500", "700"],
  subsets: ["devanagari"],
  variable: "--font-mukta",
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "दुलहिनपुर गणेशोत्सव",
//   description: "दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।",
// };



// export const metadata: Metadata = {
//   // 🚀 OPTIMIZATION 1: metadataBase (बॉट को सीधा रास्ता बताना)
//   metadataBase: new URL('https://dulahinpur-official-website.vercel.app'),
  
//   title: 'दुलहिनपुर गणेशोत्सव',
//   description: 'दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।',
  
//   openGraph: {
//     title: 'दुलहिनपुर गणेशोत्सव',
//     description: 'दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।',
//     url: '/', // metadataBase अपने आप आगे का URL जोड़ लेगा
//     siteName: 'Dulahinpur Ganesh Utsav',
//     images: [
//       {
//         // 🚀 OPTIMIZATION 2: सही साइज़ और पूरा नाम
//         url: '/og-image.jpg', 
//         width: 1200,
//         height: 630,
//         alt: 'Dulahinpur Ganesh Utsav Logo',
//       },
//     ],
//     locale: 'hi_IN',
//     type: 'website',
//   },
  
//   twitter: {
//     card: 'summary_large_image',
//     title: 'दुलहिनपुर गणेशोत्सव',
//     description: 'दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।',
//     images: ['/og-image.jpg'],
//   },
// }



export const metadata: Metadata = {
  // यहाँ से metadataBase हटा दिया गया है
  
  title: 'दुलहिनपुर गणेशोत्सव',
  description: 'दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।',
  
  openGraph: {
    title: 'दुलहिनपुर गणेशोत्सव',
    description: 'दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।',
    // 🚀 FIX: सीधा पूरा URL डाल दिया गया है
    url: 'https://dulahinpur-official-website.vercel.app/', 
    siteName: 'Dulahinpur Ganesh Utsav',
    images: [
      {
        // 🚀 FIX: इमेज के लिए भी पूरी लिंक डाल दी गई है
        url: 'https://dulahinpur-official-website.vercel.app/og-image.jpg', 
        width: 1200,
        height: 630,
        alt: 'Dulahinpur Ganesh Utsav Logo',
      },
    ],
    locale: 'hi_IN',
    type: 'website',
  },
  
  twitter: {
    card: 'summary_large_image',
    title: 'दुलहिनपुर गणेशोत्सव',
    description: 'दुलहिनपुर के भव्य गणेश उत्सव में आपका हार्दिक स्वागत है।',
    // 🚀 FIX: यहाँ भी पूरी लिंक
    images: ['https://dulahinpur-official-website.vercel.app/og-image.jpg'], 
  },
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
   return (
    <html lang="en">
      <body>
           <Loader />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}